method_name: "regression"

save_top_path: "/home/num_regression_attitude_estimator_log/test2021_07_27"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_01_image70000/"
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_02_image140000/"
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_03_image140000/"
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_04_image70000"
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_04_image140000/"
valid:
  - "/home/ssd_dir/AirSimNH/AirSimNH/2021_06_02_image70000/"
csv_name: "image_attitude.csv"

multiGPU: 1 #1 is ture

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "Adam"
  lr_cnn: 1e-5
  lr_fc: 1e-4
  batch_size: 50
  num_epochs: 50
  dropout_rate: 0.1
  dim_fc_out: 9