method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/verify_data1/"
csv_name: "image_attitude.csv"

weights_top_directory: "/home/ssd_dir/num_regression_attitude_estimator_log/train_dgx_for_comparison_2021_07_27/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/num_regression_attitude_estimator_log/infer_log/test_08_02/"
infer_log_file_name: "frame_infer_relust.csv"

resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 9
dropout_rate: 0.1
num_sampling: 15